# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: facturaagil
service: serverless-example

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-scripts

package:
  exclude:
    - .vscode/**
    - .idea/**
    - test/**
    - build/**
    - .build/**
    - my-artifacts/**

custom:
  scripts:
    hooks:
      'after:package:createDeploymentArtifacts': >
        printf "[after:package:createDeploymentArtifacts hook] Removing development dependencies " &&
        (cd .serverless && unzip -qq serverless-example.zip -d serverless-example)          && printf "." &&
        (cd .serverless && rm -rf serverless-example/node_modules)                       && printf "." &&
        (cd .serverless/serverless-example && npm install --only=prod > /dev/null 2>&1)  && printf "." &&
        (cd .serverless/serverless-example/ && zip -q -FSr ../serverless-example.zip .)     && printf ".\n" &&
        rm -rf .serverless/serverless-example/ &&
        printf "[after:package:createDeploymentArtifacts hook] Done\n"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'